### ISSUE TITLE
Suggestion: Compatibility with LittleCompany

### ISSUE THREAD

**Issue by DarkerBrightness** [Inoyuuuuu/GiantExtensionLaddersV2#2]
It would be nice if shrunken players could use the tiny extension ladder :)

**Comment by Inoyuuuuu** [comment]
I like that idea, I'll look into this (although I can't promise anything atm)! c:

**Comment by Inoyuuuuu** [comment]
Ran a few first tests and there are some issues, but - it is possible.. I may have to redesign the tiny ladder entirely tho.

Also the tests led to a "bugfix" that will be added to future patches, so thank you for that! :D 
_Bug: when starting to climb from an angle, you would climb with an offset to the left or right. 
It will now only affect the ladders of my mod instead of all ladders (annoying but necessary for mine to work properly, the bug was most notably on "map-ladders" anyway)._

**Comment by Inoyuuuuu** [comment]
Hey, the new version is out on [thunderstore](https://thunderstore.io/c/lethal-company/p/Inoyu/Giant_Extension_Ladders/) and with it comes climbing on the tiny ladder (if the person itself is tiny)! I know this took a while, but I couldn't start working on this earlier due to exams and other irl stuff. Also, the update itself proved to be quite difficult and took its time. The tiny ladder does not always work as it should, I hope you still enjoy it though! 
Thanks again for your suggestion, it helped me fix other issues and I had fun with it! c:

**Comment by DarkerBrightness** [comment]
Amazing! I'll have to try it at some point since I took a break from the game but I've been playing the v55 beta a bit. Hopefully, it doesn't affect your mods :) And great if you enjoyed working on it even if it took some time! Thank you for making mods in the first place, love all of you mod makers out there <3

**Comment by Inoyuuuuu** [comment]
Glad you enjoy them! :3
The last few updates also added ladder-stacking (ladders can be placed on other ladders) and a machine that collects all ladders on the map.
Sadly v55 had a bug that caused ladders to have no hitboxes (you are still able to use them but you will walk/fall through them). This is fixed in v56 for vanilla ladders, but still affects my stuff (I have to find out why).

**Comment by Inoyuuuuu** [comment]
fixed the bug, all ladders should work in v56 now!
